spring:
  application:
    name: order-service
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:mysql://localhost:3306/ctrpc_order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ctrpc
    password: ctrpc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true

server:
  port: 8082

# CTRPC 配置
ctrpc:
  rpc:
    server:
      port: 9092
    # 添加服务依赖：服务名 + 接口全路径
    dependencies:
      user-service:
        address: static://localhost:9091
        timeout: 3s
        interfaces:
          - com.ctrpc.iface.user.UserIface

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  file:
    path: logs
